import { toggleColor } from "../Toggle"

export const checkedColor: {[key in toggleColor]: string} = {
    amber: "peer-checked:bg-amber-500",
    amethyst: "peer-checked:bg-amethyst-500",
    aqua: "peer-checked:bg-aqua-500",
    azure: "peer-checked:bg-azure-500",
    bayoux: "peer-checked:bg-bayoux-500",
    blue: "peer-checked:bg-blue-500",
    cyan: "peer-checked:bg-cyan-500",
    emerald: "peer-checked:bg-emerald-500",
    fuchsia: "peer-checked:bg-fuchsia-500",
    green: "peer-checked:bg-green-500",
    indigo: "peer-checked:bg-indigo-500",
    jade: "peer-checked:bg-jade-500",
    jasper: "peer-checked:bg-jasper-500",
    kunzite: "peer-checked:bg-kunzite-500",
    labrodite: "peer-checked:bg-labrodite-500",
    lime: "peer-checked:bg-lime-500",
    orange: "peer-checked:bg-orange-500",
    peridot: "peer-checked:bg-peridot-500",
    pink: "peer-checked:bg-pink-500",
    purple: "peer-checked:bg-purple-500",
    red: "peer-checked:bg-red-500",
    rose: "peer-checked:bg-rose-500",
    ruby: "peer-checked:bg-ruby-500",
    russian: "peer-checked:bg-russian-500",
    scarlet: "peer-checked:bg-scarlet-500",
    stratos: "peer-checked:bg-stratos-500",
    sunstone: "peer-checked:bg-sunstone-500",
    teal: "peer-checked:bg-teal-500",
    violet: "peer-checked:bg-violet-500",
    yellow: "peer-checked:bg-yellow-500",
}