import { color } from "../../types/Generics";

export const selectColor: { [key in color]: string } = {
    amber: "hover:bg-amber-400 hover:text-amber-400 ",
    amethyst: "hover:bg-amethyst-400 hover:text-amethyst-400 ",
    aqua: "hover:bg-aqua-400 hover:text-aqua-400 ",
    azure: "hover:bg-azure-400 hover:text-azure-400 ",
    blue: "hover:bg-blue-400 hover:text-blue-400 ",
    cyan: "hover:bg-cyan-400 hover:text-cyan-400 ",
    emerald: "hover:bg-emerald-400 hover:text-emerald-400 ",
    fuchsia: "hover:bg-fuchsia-400 hover:text-fuchsia-400 ",
    green: "hover:bg-green-400 hover:text-green-400 ",
    indigo: "hover:bg-indigo-400 hover:text-indigo-400 ",
    jade: "hover:bg-jade-400 hover:text-jade-400 ",
    jasper: "hover:bg-jasper-400 hover:text-jasper-400 ",
    kunzite: "hover:bg-kunzite-400 hover:text-kunzite-400 ",
    lime: "hover:bg-lime-400 hover:text-lime-400 ",
    moonstone: "hover:bg-moonstone-400 hover:text-moonstone-400 ",
    orange: "hover:bg-orange-400 hover:text-orange-400 ",
    peridot: "hover:bg-peridot-400 hover:text-peridot-400 ",
    pink: "hover:bg-pink-400 hover:text-pink-400 ",
    purple: "hover:bg-purple-400 hover:text-purple-400 ",
    red: "hover:bg-red-400 hover:text-red-400 ",
    rose: "hover:bg-rose-400 hover:text-rose-400 ",
    ruby: "hover:bg-ruby-400 hover:text-ruby-400 ",
    russian: "hover:bg-russian-400 hover:text-russian-400 ",
    scarlet: "hover:bg-scarlet-400 hover:text-scarlet-400 ",
    stratos: "hover:bg-stratos-400 hover:text-stratos-400 ",
    sunstone: "hover:bg-sunstone-400 hover:text-sunstone-400 ",
    sylver: "hover:bg-sylver-400 hover:text-sylver-400 ",
    teal: "hover:bg-teal-400 hover:text-teal-400 ",
    violet: "hover:bg-violet-400 hover:text-violet-400 ",
    yellow: "hover:bg-yellow-400 hover:text-yellow-400 "
}