name: storybook
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - name: Build & Deploy Storybook
        run: |
          npm install
          npm run build-storybook
          npm run deploy-storybook
