name: storybook
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          node-version: '12.13.0'
      - run: |
          npm ci
          npm run build-storybook
          npm run deploy-storybook
